# Generated by Django 5.2 on 2025-05-01 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_instructorandcourse',
            name='lab_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_class_matches', to='myapp.classroom'),
        ),
        migrations.AlterField(
            model_name='match_instructorandcourse',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_class_matches', to='myapp.classroom'),
        ),
        migrations.RemoveField(
            model_name='match_instructorandcourse',
            name='major',
        ),
        migrations.AddField(
            model_name='match_instructorandcourse',
            name='major',
            field=models.ManyToManyField(blank=True, to='myapp.major'),
        ),
    ]
