# Generated by Django 5.2 on 2025-05-01 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_match_instructorandcourse_lab_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.major'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('elective', 'elective'), ('supporting', 'supporting'), ('general', 'general'), ('major', 'major')], default='general', max_length=15),
        ),
    ]
