# Generated by Django 5.2 on 2025-05-02 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile_major_alter_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable_schedule',
            name='lab_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_matches', to='myapp.classroom'),
        ),
        migrations.AlterField(
            model_name='timetable_schedule',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_class', to='myapp.classroom'),
        ),
    ]
