# Generated by Django 5.2 on 2025-05-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_timetable_schedule_lab_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable_schedule',
            name='lab_time',
            field=models.BooleanField(default=False),
        ),
    ]
