# Generated by Django 5.2 on 2025-05-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_timetable_schedule_lab_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lab_rooms',
            field=models.ManyToManyField(blank=True, related_name='courses_using_as_lab', to='myapp.classroom'),
        ),
    ]
