# Generated by Django 5.2 on 2025-05-05 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_course_lab_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabroomUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_room', models.CharField(max_length=15, unique=True)),
                ('lab_hours', models.IntegerField(blank=True, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.classroom')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.semester')),
            ],
        ),
    ]
