# Generated by Django 5.2 on 2025-05-05 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_labroomused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='semesters',
        ),
        migrations.AddField(
            model_name='classroom',
            name='semesters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.semester'),
        ),
    ]
