# Generated by Django 5.2 on 2025-05-05 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_classroom_semesters_classroom_semesters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lab_rooms',
        ),
        migrations.AddField(
            model_name='labroomused',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
    ]
